# Generated by Django 6.0.6 on 2026-06-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTarea',
            fields=[
                ('idAsignacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fechaAsignacion', models.DateField(auto_now_add=True)),
                ('fechaInicio', models.DateField()),
                ('fechaFinalizacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Media', max_length=10)),
                ('horasEstimadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horasReales', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'asignacion_tareas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('idOperario', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=100)),
                ('fechaIngreso', models.DateField()),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'db_table': 'operarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('idOrden', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('fechaEntregaEstimada', models.DateField(blank=True, null=True)),
                ('instrucciones', models.CharField(max_length=1000)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precioUnitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prioridad', models.CharField(default='Normal', max_length=10)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
            ],
            options={
                'db_table': 'ordenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idTarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTarea', models.CharField(max_length=150)),
                ('descripcionTarea', models.TextField()),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('proceso', models.CharField(max_length=100)),
                ('complejidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
            ],
            options={
                'db_table': 'tareas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correoElectronico', models.CharField(max_length=200, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('operario', 'Operario'), ('cliente', 'Cliente')], default='cliente', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('reportado', 'Reportado')], default='activo', max_length=20)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
