# Generated by Django 4.2.30 on 2026-07-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('idIncidencia', models.AutoField(primary_key=True, serialize=False)),
                ('tipoIncidencia', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Generado', 'Generado'), ('Revisado', 'Revisado'), ('Pendiente', 'Pendiente')], default='Generado', max_length=30)),
                ('fechaGeneracion', models.DateField(auto_now_add=True)),
                ('fechaRevision', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incidencias',
                'managed': False,
            },
        ),
    ]
