# Generated by Django 6.1 on 2026-08-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_incidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idInventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadDisponible', models.IntegerField(default=0)),
                ('minimoDefinido', models.IntegerField(default=0)),
                ('nivelStock', models.IntegerField(default=0)),
                ('unidades', models.CharField(default='Unidades', max_length=50)),
                ('ubicacion', models.CharField(max_length=150)),
                ('fechaActualizacion', models.DateField(auto_now=True)),
                ('cantidadIngresada', models.IntegerField(default=0)),
                ('cantidadEgresada', models.IntegerField(default=0)),
                ('fechaIngreso', models.DateField()),
                ('fechaSalida', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idMaterial', models.AutoField(db_column='idMaterial', primary_key=True, serialize=False)),
                ('nombreMaterial', models.CharField(db_column='nombreMaterial', max_length=100)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('stockActual', models.DecimalField(db_column='stockActual', decimal_places=2, max_digits=10)),
                ('stockMinimo', models.DecimalField(db_column='stockMinimo', decimal_places=2, max_digits=10)),
                ('unidadBase', models.CharField(db_column='unidadBase', max_length=50)),
                ('costoUnitario', models.DecimalField(db_column='costoUnitario', decimal_places=2, max_digits=10)),
                ('fechaActualizacion', models.DateField(auto_now=True, db_column='fechaActualizacion')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'materiales',
            },
        ),
    ]
