# Generated by Django 6.1 on 2026-08-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_inventario_producto_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.AutoField(primary_key=True, serialize=False)),
                ('numeroFactura', models.CharField(max_length=30, unique=True)),
                ('fechaEmision', models.DateTimeField(auto_now_add=True)),
                ('fechaPago', models.DateTimeField(blank=True, null=True)),
                ('rutaPDF', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Pendiente de pago', 'Pendiente de pago'), ('Pagada', 'Pagada')], default='Pendiente de pago', max_length=20)),
            ],
            options={
                'db_table': 'facturas',
                'managed': False,
            },
        ),
    ]
