# Generated by Django 4.2.30 on 2026-07-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTarea',
            fields=[
                ('idAsignacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fechaAsignacion', models.DateField(auto_now_add=True)),
                ('fechaInicio', models.DateField()),
                ('fechaFinalizacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('prioridad', models.CharField(default='Media', max_length=10)),
                ('horasEstimadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horasReales', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'asignacion_tareas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('idIncidencia', models.AutoField(primary_key=True, serialize=False)),
                ('tipoIncidencia', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('periodoEvaluado', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(default='Generado', max_length=30)),
                ('fechaGeneracion', models.DateField()),
                ('fechaRevision', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incidencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('idOperario', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=100)),
                ('fechaIngreso', models.DateField()),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'db_table': 'operarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idTarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTarea', models.CharField(max_length=150)),
                ('descripcionTarea', models.TextField()),
                ('fechaCreacion', models.DateField()),
                ('proceso', models.CharField(max_length=100)),
                ('complejidad', models.CharField(default='media', max_length=10)),
            ],
            options={
                'db_table': 'tareas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correoElectronico', models.CharField(max_length=200, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.CharField(default='operario', max_length=20)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
