# Generated by Django 6.1 on 2026-08-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.AutoField(primary_key=True, serialize=False)),
                ('numeroFactura', models.CharField(max_length=30, unique=True)),
                ('fechaEmision', models.DateTimeField(auto_now_add=True)),
                ('rutaPDF', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='Emitida', max_length=20)),
            ],
            options={
                'db_table': 'facturas',
                'managed': False,
            },
        ),
    ]
