# Generated by Django 6.1 on 2026-08-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('idCotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotalEstimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Revisada', 'Revisada'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cotizaciones',
                'ordering': ['-fechaCreacion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('idNotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('orden', 'Cambio de estado de orden'), ('factura', 'Factura emitida'), ('sistema', 'Mensaje del sistema')], default='orden', max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-fechaCreacion'],
                'managed': False,
            },
        ),
    ]
