# Generated by Django 6.0.6 on 2026-06-17 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('idPrenda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('categoria', models.CharField(choices=[('Camisa', 'Camisa'), ('Pantalón', 'Pantalón'), ('Uniforme', 'Uniforme'), ('Chaqueta', 'Chaqueta'), ('Accesorio', 'Accesorio')], max_length=20)),
                ('tallas', models.CharField(default='Única', max_length=100)),
                ('tiempoMinutos', models.IntegerField(default=30)),
                ('stockObjetivo', models.IntegerField(default=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('En pausa', 'En pausa'), ('Descontinuado', 'Descontinuado')], default='Activo', max_length=20)),
            ],
            options={
                'db_table': 'prendas',
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('idOrdenProduccion', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('cliente', models.CharField(default='Sin cliente', max_length=150)),
                ('cantidad', models.IntegerField()),
                ('producidas', models.IntegerField(default=0)),
                ('operario', models.CharField(default='Sin asignar', max_length=150)),
                ('lineaProduccion', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaEntrega', models.DateField()),
                ('prioridad', models.CharField(choices=[('Normal', 'Normal'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Normal', max_length=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado'), ('Pausado', 'Pausado')], default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('idPrenda', models.ForeignKey(db_column='idPrenda', on_delete=django.db.models.deletion.CASCADE, to='produccion.prenda')),
            ],
            options={
                'db_table': 'ordenes_produccion',
            },
        ),
    ]
