# Generated by Django 4.2.30 on 2026-06-18 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenproduccion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prenda',
            options={'managed': False},
        ),
    ]
