# Generated by Django 6.0.6 on 2026-06-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_alter_ordenproduccion_options_alter_prenda_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('idProduccion', models.AutoField(primary_key=True, serialize=False)),
                ('idOrden', models.IntegerField(blank=True, db_column='idOrden', null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidadRequerida', models.IntegerField()),
                ('fechaInicio', models.DateField()),
                ('fechaEstimadaFin', models.DateField()),
                ('fechaRealFin', models.DateField(blank=True, null=True)),
                ('costoEstimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costoReal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completado', 'Completado'), ('Detenido', 'Detenido')], default='Pendiente', max_length=20)),
            ],
            options={
                'db_table': 'produccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('Camisa', 'Camisa'), ('Pantalón', 'Pantalón'), ('Uniforme', 'Uniforme'), ('Chaqueta', 'Chaqueta'), ('Accesorio', 'Accesorio')], max_length=100)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='OrdenProduccion',
        ),
        migrations.DeleteModel(
            name='Prenda',
        ),
    ]
