# Generated by Django 4.2.30 on 2026-07-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEmpresa', models.CharField(db_column='nombreEmpresa', max_length=150)),
                ('nombreContacto', models.CharField(blank=True, db_column='nombreContacto', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, db_column='correo', max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, db_column='direccion', max_length=255, null=True)),
                ('nit', models.CharField(blank=True, db_column='nit', max_length=30, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fechaRegistro', models.DateField(db_column='fechaRegistro', default='2026-01-01')),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
    ]
