# Generated by Django 6.0.6 on 2026-06-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correoElectronico', models.CharField(max_length=200, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('operario', 'Operario'), ('cliente', 'Cliente')], default='cliente', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('reportado', 'Reportado')], default='activo', max_length=20)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
