# Generated by Django 4.2.30 on 2026-07-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('idToken', models.AutoField(primary_key=True, serialize=False)),
                ('idUsuario', models.IntegerField()),
                ('token', models.CharField(max_length=64, unique=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('expira', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'password_reset_tokens',
                'managed': False,
            },
        ),
    ]
